//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAPBotAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OOPR
    {
        public int OpprId { get; set; }
        public string CardCode { get; set; }
        public Nullable<int> SlpCode { get; set; }
        public Nullable<int> CprCode { get; set; }
        public Nullable<int> Source { get; set; }
        public Nullable<int> IntCat1 { get; set; }
        public Nullable<int> IntCat2 { get; set; }
        public Nullable<int> IntCat3 { get; set; }
        public Nullable<int> IntRate { get; set; }
        public Nullable<System.DateTime> OpenDate { get; set; }
        public string DifType { get; set; }
        public Nullable<System.DateTime> PredDate { get; set; }
        public Nullable<decimal> MaxSumLoc { get; set; }
        public Nullable<decimal> MaxSumSys { get; set; }
        public Nullable<decimal> WtSumLoc { get; set; }
        public Nullable<decimal> WtSumSys { get; set; }
        public Nullable<decimal> PrcnProf { get; set; }
        public Nullable<decimal> SumProfL { get; set; }
        public Nullable<decimal> SumProfS { get; set; }
        public string Memo { get; set; }
        public string Status { get; set; }
        public string StatusRem { get; set; }
        public Nullable<int> Reason { get; set; }
        public Nullable<decimal> RealSumLoc { get; set; }
        public Nullable<decimal> RealSumSys { get; set; }
        public Nullable<decimal> RealProfL { get; set; }
        public Nullable<decimal> RealProfS { get; set; }
        public Nullable<decimal> CloPrcnt { get; set; }
        public Nullable<short> StepLast { get; set; }
        public Nullable<short> UserSign { get; set; }
        public string Transfered { get; set; }
        public Nullable<short> Instance { get; set; }
        public string CardName { get; set; }
        public Nullable<System.DateTime> CloseDate { get; set; }
        public Nullable<int> LastSlp { get; set; }
        public string Name { get; set; }
        public Nullable<int> Territory { get; set; }
        public Nullable<int> Industry { get; set; }
        public string ChnCrdCode { get; set; }
        public string ChnCrdName { get; set; }
        public string PrjCode { get; set; }
        public Nullable<short> CardGroup { get; set; }
        public Nullable<int> ChnCrdCon { get; set; }
        public Nullable<int> Owner { get; set; }
        public string attachment { get; set; }
        public string DocType { get; set; }
        public Nullable<int> DocNum { get; set; }
        public Nullable<int> DocEntry { get; set; }
        public string DocChkbox { get; set; }
        public Nullable<int> AtcEntry { get; set; }
        public Nullable<int> LogInstanc { get; set; }
        public Nullable<short> UserSign2 { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string OpprType { get; set; }
    }
}
