//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAPBotAPI.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SBODemoSGEntities : DbContext
    {
        public SBODemoSGEntities()
            : base("name=SBODemoSGEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<OOPR> OOPRs { get; set; }
        public virtual DbSet<OITM> OITMs { get; set; }
        public virtual DbSet<ITM1> ITM1s { get; set; }
        public virtual DbSet<OCRD> OCRDs { get; set; }
    }
}
